### ISSUE TITLE
Add i18n

### ISSUE THREAD

**Issue by ConcernedHobbit** [TKOaly/job-board-next#4]
- Add english translations and ability to toggle language
- ~Add label indicators for working language for a job posting~ Split to #7

**Comment by dogamak** [comment]
Separate working language field is a great idea!

**Comment by ConcernedHobbit** [comment]
This ticket could be split to manage workload; I'll spin out separate language indicator into a ticket of its own, and keep this to translation.

**Comment by ConcernedHobbit** [comment]
Should also be possible to add fields in English for e.g. company names. For example the European Ombudsman is Euroopan oikeusasiamies in Finnish.

**Comment by dogamak** [comment]
Implemented i18n support and translated the page to Finnish and English. Support for multi-language fields (company name, post title and body) was also implemented.
